### ISSUE TITLE
Doesn't move on to Math Fluency after second-to-last task

### ISSUE THREAD

**Issue by shivsk93** [StanfordCosyne/dyscalculia-screener#116]
When it says there is one game left, a 404 Not Found error page comes up (at http://stanfordmathproject.com/fluency.html) Math Fluency in general doesn't seem to be working from the admin home page.

**Comment by cbattista** [comment]
I think this is fixed - works from admin page - mind doing a playthrough and seeing whether it works properly?

**Comment by shivsk93** [comment]
Yep, worked in a playthrough!

**Comment by cbattista** [comment]
great, closed
