### ISSUE TITLE
missing js in taskdata-plotter branch

### ISSUE THREAD

**Issue by cbattista** [StanfordCosyne/dyscalculia-screener#123]
http://127.0.0.1:9494/js/taskdata.js Failed to load resource: the server responded with a status of 404 (Not Found)

http://127.0.0.1:9494/js/d3.v3.js Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by boomsbloom** [comment]
on train but can push once I get to wifi. that file is also available
online in the meantime (just a copy of d3 library).

**Comment by cbattista** [comment]
yep, there's your taskdata.js file that's missing also

On Fri, Sep 18, 2015 at 6:18 PM, Jonathan Nicholas <notifications@github.com

**Comment by cbattista** [comment]
no rush but i think i got it to work on my system, at least, it's making
the json file

**Comment by boomsbloom** [comment]
yeah just saw that - my bad. didn't add before commit

**Comment by boomsbloom** [comment]
oh great!
