### ISSUE TITLE
Subject scores aren't shown

### ISSUE THREAD

**Issue by shivsk93** [StanfordCosyne/dyscalculia-screener#138]
When you go to http://araza:9696/api/subject and click on a subject number, no score data is shown. (Doesn't work on stanfordmathproject.com/api/subject either)

**Comment by cbattista** [comment]
argh, will take a look at this soon!

**Comment by boomsbloom** [comment]
So I think this is because the previous subject pages were generated using the old graphing code which is gone now

**Comment by cbattista** [comment]
yep, can close this, but should post an instruction on how to see the
subject scores in the README
