### ISSUE TITLE
Scores don't come up for /user or plot for /experimenter

### ISSUE THREAD

**Issue by shivsk93** [StanfordCosyne/dyscalculia-screener#142]
Did a test run and scores didn't show up on stanfordmathproject.com/api/user table. Broken link when you click on the timestamp within a user page

'No user data' when I entered the test run username into stanfordmathproject.com/api/experimenter (it plots older subjects' data but not recent subjects' data)

**Comment by boomsbloom** [comment]
@cbattista I committed something to the server and then reverted it
yesterday but I checked the domain after and everything was still working.

**Comment by boomsbloom** [comment]
but this could be a byproduct of that

**Comment by cbattista** [comment]
Allright, will try to get to the bottom of this this weekend.  -C

**Comment by cbattista** [comment]
ok, tracked this down to a serious data logging problem.  somehow this page - http://stanfordmathproject.com/api/subject/ - broke and so it was rejecting requests for data.  I will fix this and then we should also set up a unit test to make sure everytime we update we check that this still accepts data.

**Comment by shivsk93** [comment]
/api/subject works now!
/api/experimenter still does not
